general {
    gaps_in = 5
    gaps_out = 5, 10, 10, 10
    border_size = 2
    col.inactive_border = 0xff1e1e2e
    col.active_border = 0xff89b4fa
    allow_tearing = false
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

gesture = 3, horizontal, workspace

source = ~/.config/hypr/hyprland/input.conf
source = ~/.config/hypr/hyprland/applications.conf
source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/environments.conf
source = ~/.config/hypr/hyprland/monitors.conf
source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/windowrules.conf
source = ~/.config/hypr/hyprland/animations.conf
source = ~/.config/hypr/hyprland/decorations.conf